name: openvoice
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.9
- pip
- pip:
  - -r requirements.txt  
  - git+https://github.com/myshell-ai/MeloTTS.git
  - unidic
  - ipykernel